version: "3.3"
services:
   db:
     image: postgres:12
     restart: always
     volumes:
       - app-db-data:/var/lib/postgresql/data/pgdata
     env_file:
       - .env
     environment:
       - PGDATA=/var/lib/postgresql/data/pgdata
     deploy:
       placement:
         constraints:
           - node.labels.${STACK_NAME?Variable not set}.app-db-data == true

   pgadmin:
     image: dpage/pgadmin4
     depends_on:
       - db
     env_file:
       - .env

   milionaire-game:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    container_name: milionaire-game
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

    volumes:
      - /opt/filesystem/:/opt/filesystem/
volumes:
  app-db-data: {}
  worker: {}

networks:
  app-public:
    # Allow setting it to false for testing
    external: true
