version: "3.3"
services:

   db:
     ports:
       - "5432:5432"
     networks:
       - ${PROXY_PUBLIC_NETWORK?Variable not set}
       - default
   pgadmin:
      ports:
        - "5050:5050"



   milionaire-game:
    networks:
      - ${PROXY_PUBLIC_NETWORK?Variable not set}
      - default
    ports:
      - "9006:9006"
    volumes:
      - ./:/app
    environment:
      - JUPYTER=jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-false}
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    command: /start-reload.sh

networks:
  app-public:
    # Allow setting it to false for testing
    external: true
