"""modifying question  model

Revision ID: f0819165dbd7
Revises: 3c784ffbc244
Create Date: 2022-10-18 11:37:53.950627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0819165dbd7'
down_revision = '3c784ffbc244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('correct_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'correct_answer')
    # ### end Alembic commands ###
